{{- range .Values.namespaces }}
{{- if .create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    {{- if .istio.enabled }}
    istio-injection: "enabled"
    {{- end }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
{{- end }}
{{- end }}